### ISSUE TITLE
Key based authentication issue

### ISSUE THREAD

**Issue by rosch100** [superflexible/TGPuttyLib#5]
When I try to use key based authentication by setting KeyFile and KeyPassword, I cannot connect receiving an access denied message. I am wondering, if the implementation of tgputtysftp is complete since FKeyPassword is currently not used anywhere? What am I missing?

**Comment by superflexible** [comment]
Hi,
it's actually complete. FKeyPassword isn't used because the class uses the property KeyPassword internally too. If you set a breakpoint in getpassword_callback in the file tgputtysftp.pas, you will see if the Putty DLL prompts for the password and what the class returns.

I just tested it again here and it works for me. Maybe you can test the same key file and password with psftp or FileZilla?

**Comment by superflexible** [comment]
Or if you set the Verbose property to true, you will get very detailed messages via the OnMessage callback ...

**Comment by rosch100** [comment]
Thank you. Not sure, why I was not able to connect. Now it works as expected.
